### ISSUE TITLE
TODO list for release 0.9.5

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash_plugin_branchwater#362]
When https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/360 and https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/361 are merged, we should move to release v0.9.5 quickly!

TODO items before that wonderful day can arrive:

- [ ] update docs to mention betterplot ref https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/350
- [ ] update gather docs per https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/329
- [ ] maybe fix https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/279 just as a bonus
